import type { CorpusItem } from "../types";

// English corpora — deterministic, CC0-like curated. No runtime AI generation.
export const ENGLISH_CORPUS: CorpusItem[] = [
  {
    id: "en-sprint-001",
    text: "the quick brown fox jumps over the lazy dog while the morning sun rises over the quiet town and people begin their daily routines",
    language: "en",
    mode: "sprint",
    difficulty: "easy",
    source: "curated-en-v1",
    tags: ["common-words"],
    charCount: 120,
    wordCount: 22,
    punctuationTypes: [],
  },
  {
    id: "en-sprint-002",
    text: "practice makes progress and consistent effort builds lasting skill in every challenge we choose to pursue with patience",
    language: "en",
    mode: "sprint",
    difficulty: "easy",
    source: "curated-en-v1",
    tags: ["motivational"],
    charCount: 110,
    wordCount: 18,
    punctuationTypes: [],
  },
  {
    id: "en-sprint-003",
    text: "technology transforms how we communicate and typing remains a fundamental skill for productivity across many professions today",
    language: "en",
    mode: "sprint",
    difficulty: "medium",
    source: "curated-en-v1",
    tags: ["tech"],
    charCount: 120,
    wordCount: 17,
    punctuationTypes: [],
  },
  {
    id: "en-copypro-001",
    text: "Hello, World! This is a Copy Pro exercise: numbers (42, 3.14), symbols @#$, and Capitalized Words. Can you keep 100% accuracy?",
    language: "en",
    mode: "copy-pro",
    difficulty: "medium",
    source: "curated-en-v1",
    tags: ["punctuation", "symbols", "numbers"],
    charCount: 126,
    wordCount: 21,
    punctuationTypes: [",", "!", ":", "(", ")", ".", "?"],
  },
  {
    id: "en-copypro-002",
    text: "On 12/31/2025, Order #A-4829 was shipped to 742 Evergreen Terrace, Springfield, IL 62704. Total: $1,249.00 (incl. tax).",
    language: "en",
    mode: "copy-pro",
    difficulty: "hard",
    source: "curated-en-v1",
    tags: ["data-entry", "address", "date"],
    charCount: 118,
    wordCount: 17,
    punctuationTypes: [",", ".", "/", "#", "-", ":", "$"],
  },
  {
    id: "en-numbers-001",
    text: "Order IDs: 90421, 77304, 11289 | Phones: +1-415-555-0132, +1-212-555-0198 | Amounts: 42.50, 1,299.00, 0.99",
    language: "en",
    mode: "numbers",
    difficulty: "hard",
    source: "curated-en-v1",
    tags: ["numbers"],
    charCount: 112,
    wordCount: 14,
    punctuationTypes: [",", ":", "|", "-", ".", "+"],
  },
  {
    id: "en-punct-001",
    text: "\"Don't worry,\" she said, \"it's not that complicated — just focus on accuracy, then speed will follow naturally.\"",
    language: "en",
    mode: "punctuation",
    difficulty: "medium",
    source: "curated-en-v1",
    tags: ["dialogue", "quotes"],
    charCount: 112,
    wordCount: 18,
    punctuationTypes: ["\"", "'", ",", "—", "."],
  },
  {
    id: "en-hard-001",
    text: "The researcher's hypothesis — though unproven — suggested that deterministic adaptation could feel personalized without any generative inference at runtime.",
    language: "en",
    mode: "copy-pro",
    difficulty: "hard",
    source: "curated-en-v1",
    tags: ["complex"],
    charCount: 146,
    wordCount: 19,
    punctuationTypes: ["—", ".", ","],
  },
];

export const ENGLISH_SPRINT_POOL = ENGLISH_CORPUS.filter(c => c.mode === "sprint");
