import type { CorpusItem } from "../types";

export const INDONESIAN_CORPUS: CorpusItem[] = [
  {
    id: "id-sprint-001",
    text: "latihan mengetik cepat membutuhkan konsistensi dan fokus setiap hari agar kecepatan dan akurasi meningkat secara bertahap",
    language: "id",
    mode: "sprint",
    difficulty: "easy",
    source: "curated-id-v1",
    tags: ["common-words"],
    charCount: 112,
    wordCount: 17,
    punctuationTypes: [],
  },
  {
    id: "id-sprint-002",
    text: "kemampuan mendengar dan menulis dengan tepat sangat penting untuk pekerjaan transkripsi dan entri data profesional",
    language: "id",
    mode: "sprint",
    difficulty: "easy",
    source: "curated-id-v1",
    tags: ["transcription"],
    charCount: 108,
    wordCount: 15,
    punctuationTypes: [],
  },
  {
    id: "id-copypro-001",
    text: "Halo, Dunia! Latihan ini menguji tanda baca: angka (42, 3,14), simbol @#$, dan Huruf Kapital. Mampukah kamu 100% akurat?",
    language: "id",
    mode: "copy-pro",
    difficulty: "medium",
    source: "curated-id-v1",
    tags: ["punctuation"],
    charCount: 124,
    wordCount: 19,
    punctuationTypes: [",", "!", ":", "(", ")", ".", "?"],
  },
  {
    id: "id-numbers-001",
    text: "Pesanan: 77304 | Telepon: +62-812-3456-7890 | Jumlah: Rp1.250.000,00 dan Rp42.500,50 pada tanggal 31/12/2025",
    language: "id",
    mode: "numbers",
    difficulty: "hard",
    source: "curated-id-v1",
    tags: ["numbers", "currency"],
    charCount: 112,
    wordCount: 14,
    punctuationTypes: [":", "|", "-", ".", ",", "+"],
  },
  {
    id: "id-punct-001",
    text: "\"Jangan khawatir,\" katanya, \"ini tidak rumit — fokus pada akurasi dulu, kecepatan akan mengikuti dengan sendirinya.\"",
    language: "id",
    mode: "punctuation",
    difficulty: "medium",
    source: "curated-id-v1",
    tags: ["dialogue"],
    charCount: 114,
    wordCount: 17,
    punctuationTypes: ["\"", ",", "—", "."],
  },
];
